using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Models;
using Models.Repository;

namespace Win.sts
{
    public partial class frmStatus : DevExpress.XtraEditors.XtraForm
    {
        public frmStatus()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            entityServerModeSource1.QueryableSource = new UnitOfWork().StatusesRepo.Fetch();
        }

        private void repositoryItemButtonEdit2_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {

            if (MessageBox.Show("Do you want to delete this?", "Submit", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.No)
                return;
            if (StatusGrid.GetFocusedRow() is Statuses item)
            {
                UnitOfWork unitOfWork = new UnitOfWork();
                unitOfWork.StatusesRepo.Delete(m => m.Id == item.Id);
                unitOfWork.Save();
            }
            entityServerModeSource1.QueryableSource = new UnitOfWork().StatusesRepo.Fetch();
        }

        private void frmStatus_Load(object sender, EventArgs e)
        {

        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            frmAddEditStatus frm = new frmAddEditStatus(null, MethodType.Add);
            frm.ShowDialog();
            entityServerModeSource1.QueryableSource = new UnitOfWork().StatusesRepo.Fetch();
        }

        private void btnEdit_Click(object sender, EventArgs e)
        {
            if (StatusGrid.GetFocusedRow() is Statuses item)
            {
                frmAddEditStatus frm = new frmAddEditStatus(item, MethodType.Edit);
                frm.ShowDialog();
                entityServerModeSource1.QueryableSource = new UnitOfWork().StatusesRepo.Fetch();
            }
        }
    }
}