using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Models;
using Models.Repository;

namespace Win.PGN
{
    public partial class UCPGN : DevExpress.XtraEditors.XtraUserControl
    {
        public UCPGN()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            this.Init();
        }

        private void Init()
        {
            try
            {
                UnitOfWork unitOfWork = new UnitOfWork();
                var pgn = unitOfWork.PGNsRepo.Fetch();
                PGNServerModeSource.QueryableSource = pgn;
                this.Detail(pgn.FirstOrDefault());
            }
            catch (Exception e)
            {

            }
        }

        void Search(string search)
        {
            try
            {
                UnitOfWork unitOfWork = new UnitOfWork();
                var pgn = unitOfWork.PGNsRepo.Fetch();
                pgn = pgn.Where(x => x.RequestProblem.Contains(search) || x.ControlNo.Contains(search) || (x.EmployeeName.Contains(search)));

                PGNServerModeSource.QueryableSource = pgn;

                this.Detail(pgn.FirstOrDefault());
            }
            catch (Exception e)
            {

            }
        }

        private void Detail(PGNs pgn)
        {
            try
            {
            }
            catch (Exception e)
            {

            }
        }
    }
}
