using System.Linq;
using System.Windows.Forms;
using DevExpress.XtraGrid.Views.Grid;
using Models;
using Models.Repository;

namespace Win.MESAF
{
    public partial class ucMES : DevExpress.XtraEditors.XtraUserControl
    {
        public GridView GridView => gridView1;
        public ucMES()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard


            txtSearch.KeyDown += TxtSearch_KeyDown;
        }

        public void Create()
        {
            UnitOfWork unitOfWork = new UnitOfWork();


                entityServerModeSource1.QueryableSource = unitOfWork.MESRepo.Fetch();

        }

        private void TxtSearch_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                using (UnitOfWork unitOfWork = new UnitOfWork())
                {
                    entityServerModeSource1.QueryableSource = unitOfWork.MESRepo.Fetch().Where(m => m.Employees.LastName.Contains(txtSearch.Text) || m.MESId.Contains(txtSearch.Text));
                }
            }
        }

        private void colBtnDel_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            if (gridView1.GetFocusedRow() is MES item)
            {

                if (MessageBox.Show("Do you want to delete this?", "Submit", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.No)
                    return;
                UnitOfWork unitOfWork = new UnitOfWork();
                unitOfWork.MESRepo.Delete(m => m.Id == item.Id);
                unitOfWork.Save();
                Create();
            }
        }
    }
}
