//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deliveries()
        {
            this.EquipmentProfiles = new HashSet<EquipmentProfiles>();
        }
    
        public int Id { get; set; }
        public string DeliveryId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public byte[] Files { get; set; }
    
        public virtual Offices Offices { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentProfiles> EquipmentProfiles { get; set; }
    }
}
