//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocActions
    {
        public int Id { get; set; }
        public Nullable<int> RefId { get; set; }
        public string Status { get; set; }
        public string ActionTaken { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string CreatedBy { get; set; }
        public string TableName { get; set; }
        public string Remarks { get; set; }
        public string EndorsedTo { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> MainActivityId { get; set; }
        public Nullable<int> SubActivityId { get; set; }
        public Nullable<int> ActivityId { get; set; }
    
        public virtual PPEs PPEs { get; set; }
        public virtual TechSpecs TechSpecs { get; set; }
        public virtual Users CreatedByUsers { get; set; }
        public virtual Users EndorsedToUsers { get; set; }
        public virtual WorkOrders WorkOrders { get; set; }
    }
}
