//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentProfiles
    {
        public int Id { get; set; }
        public Nullable<int> RefId { get; set; }
        public string TableName { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public Nullable<int> EquipmentTypeId { get; set; }
        public string EquipmentName { get; set; }
        public string Description { get; set; }
        public Nullable<int> UnitTypeId { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Remarks { get; set; }
        public string ActualModel { get; set; }
        public string Serial { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ParentItem { get; set; }
        public string EquipmentType { get; set; }
    
        public virtual EquipmentTypes EquipmentTypes { get; set; }
        public virtual PPEs PPEs { get; set; }
        public virtual UnitTypes UnitTypes { get; set; }
        public virtual PurchaseOrders PurchaseOrders { get; set; }
        public virtual TechSpecs TechSpecs { get; set; }
        public virtual TechSpecEquipmentProfiles TechSpecEquipmentProfiles { get; set; }
        public virtual Deliveries Deliveries { get; set; }
    }
}
