//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES
    {
        public int Id { get; set; }
        public string MESId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Position { get; set; }
        public string ItemSpec { get; set; }
        public string Request { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<int> DeliveredBy { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Offices Offices { get; set; }
    }
}
