//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelDb : DbContext
    {
        public ModelDb()
            : base("name=ModelDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EquipmentTypes> EquipmentTypes { get; set; }
        public virtual DbSet<Actions> Actions { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Provinces> Provinces { get; set; }
        public virtual DbSet<Towns> Towns { get; set; }
        public virtual DbSet<UserClaims> UserClaims { get; set; }
        public virtual DbSet<UserLogins> UserLogins { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<UserRolesInActions> UserRolesInActions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UnitTypes> UnitTypes { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<PPEs> PPEs { get; set; }
        public virtual DbSet<WorkOrders> WorkOrders { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<DocActions> DocActions { get; set; }
        public virtual DbSet<EquipmentProfiles> EquipmentProfiles { get; set; }
        public virtual DbSet<EvaluationSheets> EvaluationSheets { get; set; }
        public virtual DbSet<TechnicalEvaluationSheet> TechnicalEvaluationSheet { get; set; }
        public virtual DbSet<PurchaseOrders> PurchaseOrders { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<Articles> Articles { get; set; }
        public virtual DbSet<TechSpecs> TechSpecs { get; set; }
        public virtual DbSet<Offices> Offices { get; set; }
        public virtual DbSet<TechSpecRequests> TechSpecRequests { get; set; }
        public virtual DbSet<TechSpecEquipmentProfiles> TechSpecEquipmentProfiles { get; set; }
        public virtual DbSet<MES> MES { get; set; }
        public virtual DbSet<Deliveries> Deliveries { get; set; }
        public virtual DbSet<Dropdowns> Dropdowns { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
    }
}
