//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechSpecRequests
    {
        public int Id { get; set; }
        public Nullable<int> TechSpecsId { get; set; }
        public Nullable<int> Qty { get; set; }
        public string EquipmentType { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string Purpose { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ItemNumber { get; set; }
    
        public virtual TechSpecs TechSpecs { get; set; }
    }
}
