//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechSpecs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechSpecs()
        {
            this.EquipmentProfiles = new HashSet<EquipmentProfiles>();
            this.TechSpecRequests = new HashSet<TechSpecRequests>();
            this.DocActions = new HashSet<DocActions>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Requestedby { get; set; }
        public Nullable<int> EquipmentType { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string AssignedTo { get; set; }
        public string SpecType { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public string TableName { get; set; }
        public Nullable<int> WorOrderId { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentProfiles> EquipmentProfiles { get; set; }
        public virtual EquipmentTypes EquipmentTypes { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechSpecRequests> TechSpecRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocActions> DocActions { get; set; }
        public virtual WorkOrders WorkOrders { get; set; }
    }
}
