//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrders()
        {
            this.DocActions = new HashSet<DocActions>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PPEId { get; set; }
        public string WorkOrderId { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<int> RequestedBy { get; set; }
        public string Position { get; set; }
        public string Problem { get; set; }
        public string AssignedTo { get; set; }
        public string Findings { get; set; }
        public string Recommendation { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> Box { get; set; }
        public string FolderNo { get; set; }
        public Nullable<int> BoxNo { get; set; }
        public string CreatedBy { get; set; }
        public string DeliveredBy { get; set; }
        public string DeliveredDescription { get; set; }
    
        public virtual PPEs PPEs { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocActions> DocActions { get; set; }
        public virtual Users CreatedByUser { get; set; }
    }
}
